import type { ProjectType } from './types';

export const projects: ProjectType[] = [
  {
    id: 1,
    title: 'Character Design Series',
    description: 'Digital character illustrations exploring different art styles and personalities. Created for a fantasy game concept.',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=400&fit=crop',
    category: 'Illustration',
    tools: ['Procreate', 'Adobe Illustrator', 'Photoshop'],
    year: '2024',
    behanceUrl: 'https://behance.net/gallery/character-design',
    instagramUrl: 'https://instagram.com/p/character-post',
  },
  {
    id: 2,
    title: 'Architectural Visualization',
    description: 'Photorealistic 3D renders of modern residential buildings with detailed lighting and material work.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop',
    category: '3D',
    tools: ['Blender', 'Cycles Renderer', 'Photoshop'],
    year: '2024',
    behanceUrl: 'https://behance.net/gallery/architectural-viz',
  },
  {
    id: 3,
    title: 'Urban Sketching Collection',
    description: 'Hand-drawn sketches capturing the essence of city life, architecture, and street scenes.',
    image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600&h=400&fit=crop',
    category: 'Sketch',
    tools: ['Pencil', 'Ink', 'Watercolor', 'iPad Pro'],
    year: '2023',
    instagramUrl: 'https://instagram.com/p/urban-sketches',
  },
  {
    id: 4,
    title: 'Fashion Photography Retouching',
    description: 'Professional photo editing and retouching for fashion brands, enhancing colors, skin, and overall aesthetics.',
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&h=400&fit=crop',
    category: 'Photo Editing',
    tools: ['Photoshop', 'Lightroom', 'Capture One'],
    year: '2024',
    behanceUrl: 'https://behance.net/gallery/fashion-retouching',
  },
  {
    id: 5,
    title: 'Product Design Concepts',
    description: 'Detailed product illustrations and concept art for consumer electronics and gadgets.',
    image: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600&h=400&fit=crop',
    category: 'Illustration',
    tools: ['Adobe Illustrator', 'Figma', 'Sketch'],
    year: '2024',
    behanceUrl: 'https://behance.net/gallery/product-concepts',
  },
  {
    id: 6,
    title: 'Abstract 3D Art',
    description: 'Experimental 3D compositions exploring form, color, and movement in digital space.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&h=400&fit=crop',
    category: '3D',
    tools: ['Cinema 4D', 'Octane Render', 'After Effects'],
    year: '2023',
    instagramUrl: 'https://instagram.com/p/abstract-3d',
  },
  {
    id: 7,
    title: 'Portrait Studies',
    description: 'Traditional and digital portrait sketches focusing on expression, lighting, and human anatomy.',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&h=400&fit=crop',
    category: 'Sketch',
    tools: ['Charcoal', 'Graphite', 'Procreate'],
    year: '2023',
    instagramUrl: 'https://instagram.com/p/portrait-studies',
  },
  {
    id: 8,
    title: 'Landscape Photo Manipulation',
    description: 'Creative photo manipulation and compositing work transforming ordinary landscapes into fantastical scenes.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
    category: 'Photo Editing',
    tools: ['Photoshop', 'Lightroom', 'AI Tools'],
    year: '2024',
    behanceUrl: 'https://behance.net/gallery/landscape-manipulation',
  },
];
